// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Layout: typeof import('./src/components/Layout/Layout.vue')['default']
    LayoutHeader: typeof import('./src/components/Layout/components/LayoutHeader.vue')['default']
    LayoutHeaderSearch: typeof import('./src/components/Layout/components/LayoutHeaderSearch.vue')['default']
    LayoutLeftMenu: typeof import('./src/components/Layout/components/LayoutLeftMenu.vue')['default']
    LoadImg: typeof import('./src/components/Base/LoadImg.vue')['default']
    LoadImg1: typeof import('./src/components/Base/LoadImg1.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCarouselItem: typeof import('naive-ui')['NCarouselItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopover: typeof import('naive-ui')['NPopover']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSwitch: typeof import('naive-ui')['NSwitch']
    PlayIcon: typeof import('./src/components/Base/PlayIcon.vue')['default']
    SongList: typeof import('./src/components/SongsList/SongList.vue')['default']
    SongListSkeleton: typeof import('./src/components/SongsList/SongListSkeleton.vue')['default']
  }
}

export { }
